services:
  backend:
    build: .
    ports:
      - "8501:8501"  # Streamlit
    volumes:
      - ./data:/app/data  # For dynamic data if needed
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_MAX_DOCS=5
      - RAG_MIN_RELEVANCE=0.3
      - ESCALATION_THRESHOLD=0.6
      - PYTHONPATH=/app
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0

  # Frontend service (placeholder - add when frontend is available)
  # frontend:
  #   build: ./frontend  # Assuming frontend in subdir
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
